### ISSUE TITLE
Alert component

### ISSUE THREAD

**Issue by cfasol** [Davi0k/Social#1]
Il componente alert presenta una proprietà self che non è inizializzata alla quale viene invocato il metodo destroy al metodo remove é corretto....?

**Comment by Davi0k** [comment]
Sì, la proprietà `self` viene assegnata in `AlertService` nel momento in cui il metodo `trigger(type: string)` viene invocato per creare dinamicamente un `AlertComponent`. `self` contiene un riferimento al componente nativo stesso per poterlo appunto distruggere una volta che l'alert è stata letta.
